start:
	docker compose up -d
	docker run -i -v ./appsettings.json:/app/appsettings.json noteapp

start-app:
	docker run -i -v ./appsettings.json:/app/appsettings.json noteapp

start-postgres:
	docker compose up -d